# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19L_T2g1TuWD7rUt7H9nNja3K52m3pSKG
"""

import streamlit as st
api_key = st.secrets["GEMINI_API_KEY"]

st.title("QNA_CHATBOT")





# """START MAKING CHATBOT USING LANGCHAIN"""

# from google.colab import userdata
# api_key=userdata.get('GEMINI_API_KEY')

from langchain_google_genai import ChatGoogleGenerativeAI

# now create a llm
LLM = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash",
    google_api_key=api_key
)

# ques = "who is the president of india"

# result = LLM.invoke(ques)

# print(result.content)

# """NOW PLACE THE LOOP FOR MULTIPLE TIME QUESTION ANSWERS

# """



# while True:
#   user_input = input("Enter your Question:")
#   if user_input.lower() in ["bye", "quit", "exit"]:
#     print("GoodBye👋")
#   res = LLM.invoke(user_input)
#   print("AI",res.content)

# streamlit
import streamlit as st
st.title("ASK BUDDY AI QNA BOT 🤖")

st.markdown(
    """THIS CHATBOT IS USUALLY GENERATE TO GIVE THE USER THE OUTPUT AS PER THEIR
       INPUT. THIS IS A QNA CHATBOT.""")
# chating section----------------------------------------

query = st.chat_input("Ask Anything?")

# creating the session state

if "messages" not in st.session_state:
  st.session_state.messages = []

for message in st.session_state.messages:
  role = message["role"]
  content = message["content"]
  st.chat_message(role).markdown(content)

# condition for message so that it display---------------
# now the llm turn to understand this and creating the messages----

if query:
  st.session_state.messages.append({"role":"user","content":query})
  st.chat_message("user").markdown(query)
  res = LLM.invoke(query)
  st.session_state.messages.append({"role":"ai","content":res.content})
  st.chat_message("ai").markdown(res.content)

# query = st.chat_input("Ask Anything?")



